export interface Furniture {
  id: number;
  title: string;
  category: string;
  price: number; // Updated to number
  image: string;
  description: string;
}

export const furnitures: Furniture[] = [
  {
    id: 1,
    image: "/living/img2 (1).jpg",
    title: "Living Product 1",
    price: 35000,
    category: "bedroom",
    description: "Traditionally beautiful",
  },
  {
    id: 2,
    image: "/living/img2 (3).jpg",
    title: "Living Product 2",
    price: 45000,
    category: "living",
    description: "Lovely design and texture for you",
  },
  {
    id: 3,
    image: "/living/img2 (3).jpg",
    title: "Living Product 3",
    price: 95000,
    category: "dining",
    description: "Exquisite design",
  },
  {
    id: 4,
    image: "/living/img2 (3).jpg",
    title: "Office Product 1",
    price: 205000,
    category: "office",
    description: "Stylish and modern",
  },
  {
    id: 5,
    image: "/living/img2 (1).jpg",
    title: "Living Product 1",
    price: 35000,
    category: "bedroom",
    description: "Traditionally beautiful",
  },
  {
    id: 6,
    image: "/living/img2 (3).jpg",
    title: "Living Product 2",
    price: 45000,
    category: "living",
    description: "Lovely design and texture for you",
  },
  {
    id: 7,
    image: "/living/img2 (3).jpg",
    title: "Living Product 3",
    price: 95000,
    category: "dining",
    description: "Exquisite design",
  },
  {
    id: 8,
    image: "/living/img2 (3).jpg",
    title: "Office Product 1",
    price: 205000,
    category: "office",
    description: "Stylish and modern",
  },
  {
    id: 9,
    image: "/living/img2 (1).jpg",
    title: "Living Product 1",
    price: 35000,
    category: "bedroom",
    description: "Traditionally beautiful",
  },
  {
    id: 10,
    image: "/living/img2 (3).jpg",
    title: "Living Product 2",
    price: 45000,
    category: "living",
    description: "Lovely design and texture for you",
  },
  {
    id: 11,
    image: "/living/img2 (3).jpg",
    title: "Living Product 3",
    price: 95000,
    category: "dining",
    description: "Exquisite design",
  },
  {
    id: 12,
    image: "/living/img2 (3).jpg",
    title: "Office Product 1",
    price: 205000,
    category: "office",
    description: "Stylish and modern",
  },
  {
    id: 13,
    image: "/living/img2 (1).jpg",
    title: "Living Product 1",
    price: 35000,
    category: "bedroom",
    description: "Traditionally beautiful",
  },
  {
    id: 14,
    image: "/living/img2 (3).jpg",
    title: "Living Product 2",
    price: 45000,
    category: "living",
    description: "Lovely design and texture for you",
  },
  {
    id: 15,
    image: "/living/img2 (3).jpg",
    title: "Living Product 3",
    price: 95000,
    category: "dining",
    description: "Exquisite design",
  },
  {
    id: 16,
    image: "/living/img2 (3).jpg",
    title: "Office Product 1",
    price: 205000,
    category: "office",
    description: "Stylish and modern",
  },
  {
    id: 17,
    image: "/living/img2 (1).jpg",
    title: "Living Product 1",
    price: 35000,
    category: "bedroom",
    description: "Traditionally beautiful",
  },
  {
    id: 18,
    image: "/living/img2 (3).jpg",
    title: "Living Product 2",
    price: 45000,
    category: "living",
    description: "Lovely design and texture for you",
  },
  {
    id: 19,
    image: "/living/img2 (3).jpg",
    title: "Living Product 3",
    price: 95000,
    category: "dining",
    description: "Exquisite design",
  },
  {
    id: 20,
    image: "/living/img2 (3).jpg",
    title: "Office Product 1",
    price: 205000,
    category: "office",
    description: "Stylish and modern",
  },
  {
    id: 21,
    image: "/living/img2 (1).jpg",
    title: "Living Product 1",
    price: 35000,
    category: "bedroom",
    description: "Traditionally beautiful",
  },
  {
    id: 22,
    image: "/living/img2 (3).jpg",
    title: "Living Product 2",
    price: 45000,
    category: "living",
    description: "Lovely design and texture for you",
  },
  {
    id: 23,
    image: "/living/img2 (3).jpg",
    title: "Living Product 3",
    price: 95000,
    category: "dining",
    description: "Exquisite design",
  },
  {
    id: 24,
    image: "/living/img2 (3).jpg",
    title: "Office Product 1",
    price: 205000,
    category: "office",
    description: "Stylish and modern",
  },
  {
    id: 25,
    image: "/living/img2 (1).jpg",
    title: "Living Product 1",
    price: 35000,
    category: "bedroom",
    description: "Traditionally beautiful",
  },
  {
    id: 26,
    image: "/living/img2 (3).jpg",
    title: "Living Product 2",
    price: 45000,
    category: "living",
    description: "Lovely design and texture for you",
  },
  {
    id: 27,
    image: "/living/img2 (3).jpg",
    title: "Living Product 3",
    price: 95000,
    category: "dining",
    description: "Exquisite design",
  },
  // Add the rest of the furniture data here
];
